name: commitServer

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
    # - name: Work around permission issue #https://github.blog/2022-04-12-git-security-vulnerability-announced/
    #   run: |
    #     git config --global --add safe.directory ${{ github.workspace }}
    #     git config --global --add safe.directory /github/workspace
    #     git config --global --add safe.directory /home
    # 切换分支
    - name: Checkout
      uses: actions/checkout@master
    # 下载 git submodule
    # - uses: srt32/git-actions@v0.0.3
    #   with:
    #     args: git submodule update --init --recursive
    # 使用 node
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

  # npm install
    - name: npm and yarn install
      run: |
        npm install -g yarn
        yarn install
      env:
        CI: true
    # Deploy
    - name: Deploy
      uses: easingthemes/ssh-deploy@v2.0.7
      env:
        SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
        ARGS: "-avz --delete"
        SOURCE: "/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.TARGET }}
    
